CREATE TABLE [dbo].[Airports] (
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] VARCHAR (50) NOT NULL,
	[City] VARCHAR (50) NOT NULL,
	[Country] VARCHAR (50) NOT NULL, 
    [Status] NVARCHAR(250) NULL
);

